[package]
name = "sae-burn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
burn = { version = "0.13.2", features = ["wgpu", "train", "vision"] }
derive-new = "0.6.0"
project-root = "0.2.2"
